---
title: "15-Wind and Evapo"
author: "Abi Riley"
date: "2024-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "Z:/home")

```

## Packages 

```{r packages, echo= FALSE}

library(ncdf4)
library(terra)
library(readxl)
library(ggplot2)
#library(reshape2)
#library(scico)
library(dplyr)
library(tidyr)
library(sf)
library(DescTools)

```

Load in data

```{r data}

era.nc <- rast("Objective 1/Data/Climate/ERA5-Land Wind and Evap/data.nc")

```

Project, crop and create a dataframe for all variables.

```{r loop}
bbox <- rast(ncol=88, nrow=90, 
             xmin=500000, xmax=588000,
             ymin=135000, ymax=225000,
             crs = "EPSG:27700")


era.nc <- project(era.nc, bbox)
ERA <- crop(era.nc, bbox)
ERA.df <- as.data.frame(ERA, xy = TRUE)

```

Spilt into variables

```{r split}

names(ERA.df)

wind_u.df <- cbind(ERA.df[,c(1,2)], ERA.df[,grepl("u", names(ERA.df))])
wind_v.df <- cbind(ERA.df[,c(1,2)], ERA.df[,grepl("v", names(ERA.df))])
evapo.df <- cbind(ERA.df[,c(1,2)], ERA.df[,grepl("e", names(ERA.df))])


```

Convert wide to long and save DF

```{r df}

wind_u <- pivot_longer(wind_u.df, cols = !c("x", "y"), names_to = "Time", values_to = "Wind_u")
wind_v <- pivot_longer(wind_v.df, cols = !c("x", "y"), names_to = "Time", values_to = "Wind_v")
evapo <- pivot_longer(evapo.df, cols = !c("x", "y"), names_to = "Time", values_to = "Evapo")

head(wind_u)

wind_u$Time <- as.numeric(unlist(strsplit(wind_u$Time, split='_', fixed=TRUE))[c(FALSE, TRUE)])
wind_v$Time <- as.numeric(unlist(strsplit(wind_v$Time, split='_', fixed=TRUE))[c(FALSE, TRUE)])
evapo$Time <- as.numeric(unlist(strsplit(evapo$Time, split='_', fixed=TRUE))[c(FALSE, TRUE)])

era5.df <- cbind(wind_u, wind_v$Wind_v, evapo$Evapo)
names(era5.df)[c(5,6)] <- c("Wind_v", "Evapo")

save(era5.df, file = "DATA/Data/13-Wind and Evapo.RData")


```
