---
title: "16-AQUM"
output: html_document
date: "2024-005-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "Z:/home")

```

## Packages 

```{r packages, echo= FALSE}

library(terra)
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyr)
library(sf)
library(stringr)

```

Create intended grid 

```{r grid}

x <- rep(seq(500500, 587500, 1000), 88)
y.coords <- rep(seq(153500, 224500, 1000), 90)
y <- y.coords[order(y.coords)]
empty <- as.data.frame(cbind(x, y))


empty$id <- 1:nrow(empty)

grid <- terra::rast(empty, type = "xyz", crs ="+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.999601272 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs")

TTW <- read_sf("Jobs/ST_INLA/Shapefiles/Travel_to_Work_Areas_(Dec_2011)_FEB_in_United_Kingdom.shp")
London2 <- subset(TTW, OBJECTID == 92 | OBJECTID == 122)


```

Load in data

```{r data}

PM25 <- read.csv("DATA/Data/Monthly_Mean_PM2p5_Gridded_-4806054067737628141.csv")

head(PM25)

years <- c("2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")

PM25.years <- PM25 %>%
  filter(grepl(paste(years, collapse = "|"), PM25$stdTime))

PM25.years$month <- as.numeric(str_split_i(PM25.years$stdTime, "/", 1))
PM25.years$Year <- as.numeric(str_split_i(str_split_i(PM25.years$stdTime, "/", 3), " ", 1))

PM25.years$Time <- (PM25.years$Year - 2010)*12 + PM25.years$month





```




```{r process1011}

### GRID
x <- rep(unique(PM25.years$longitude), length(unique(PM25.years$latitude)))
y.coords <- rep(unique(PM25.years$latitude), length(unique(PM25.years$longitude)))
y <- y.coords[order(y.coords)]
empty <- as.data.frame(cbind(x, y))

empty$id <- 1:nrow(empty)

grid.model <- terra::rast(empty, type = "xyz", crs = "+proj=longlat +datum=WGS84 +no_defs")

### PROCESSING
PM25.df <- list()
PM25.DF <- data.frame(matrix(ncol = 4, nrow = 0))
x <- c("x", "y", "PM25", "Time")
colnames(PM25.DF) <- x

for (i in 1:120){
  PM25 <- subset(PM25.years, Time == i)
  
  PM25.grid <- merge(empty, PM25, by.x = c("x","y"), by.y = c("longitude","latitude"), all.x = FALSE, all.y = TRUE)
  
  PM25.r <- rast(PM25.grid, type = "xyz", crs = "+proj=longlat +datum=WGS84 +no_defs")
  
  PM25 <- terra::project(PM25.r, grid, method = "cubic")
  PM25 <- crop(PM25, grid)
  PM25.df[[i]] <- as.data.frame(PM25, xy = TRUE)[,c(1,2,9,12,13,14)]
  names(PM25.df[[i]])[3] <- "PM25"
  PM25.DF <- rbind(PM25.DF, PM25.df[[i]])
}


save(PM25.DF, file = "DATA/data/20-Met Office Reanalysis PM25 Cubic.RData")

```


```{r plot}

PM25 <- project(PM25.r, grid, method = "bilinear")
  
plot(PM25$mean)

PM25 <- project(PM25.r, grid, method = "cubic")
  
plot(PM25$mean)

PM25 <- project(PM25.r, grid, method = "cubicspline")
  
plot(PM25$mean)

PM25 <- project(PM25.r, grid, method = "lanczos")
  
plot

PM25 <- project(PM25.r, grid, method = "sum")
  
plot(PM25$mean)


```
NO2

Load in data

```{r data}

NO2 <- read.csv("DATA/Data/Monthly_Mean_NO2_Gridded_7598535460444771713.csv")

head(NO2)

years <- c("2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")

NO2.years <- NO2 %>%
  filter(grepl(paste(years, collapse = "|"), NO2$stdTime))

NO2.years$month <- as.numeric(str_split_i(NO2.years$stdTime, "/", 1))
NO2.years$Year <- as.numeric(str_split_i(str_split_i(NO2.years$stdTime, "/", 3), " ", 1))

NO2.years$Time <- (NO2.years$Year - 2010)*12 + NO2.years$month


```



```{r process1011}

### GRID
x <- rep(unique(NO2.years$longitude), length(unique(NO2.years$latitude)))
y.coords <- rep(unique(NO2.years$latitude), length(unique(NO2.years$longitude)))
y <- y.coords[order(y.coords)]
empty <- as.data.frame(cbind(x, y))

empty$id <- 1:nrow(empty)

grid.model <- terra::rast(empty, type = "xyz", crs = "+proj=longlat +datum=WGS84 +no_defs")

### PROCESSING
NO2.df <- list()
NO2.DF <- data.frame(matrix(ncol = 4, nrow = 0))
x <- c("x", "y", "NO2", "Time")
colnames(NO2.DF) <- x

for (i in 1:120){
  NO2 <- subset(NO2.years, Time == i)
  
  NO2.grid <- merge(empty, NO2, by.x = c("x","y"), by.y = c("longitude","latitude"), all.x = FALSE, all.y = TRUE)
  
  NO2.r <- rast(NO2.grid, type = "xyz", crs = "+proj=longlat +datum=WGS84 +no_defs")
  
  NO2 <- terra::project(NO2.r, grid, method = "cubic")
  NO2 <- crop(NO2, grid)
  NO2.df[[i]] <- as.data.frame(NO2, xy = TRUE)[,c(1,2,9,12,13,14)]
  names(NO2.df[[i]])[3] <- "NO2"
  NO2.DF <- rbind(NO2.DF, NO2.df[[i]])
}


save(NO2.DF, file = "DATA/data/20-Met Office Reanalysis NO2 Cubic.RData")

```